[package]
name = "panplexity"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
noodles = { version = "0.87.0", features = ["bgzf"] }
log = "0.4.27"
env_logger = "0.11.8"
